# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies client
      run: dotnet restore
      working-directory: ./01/client/

    - name: Build client
      run: dotnet publish --no-restore
      working-directory: ./01/client/

    - name: Restore dependencies doc client
      run: dotnet restore
      working-directory: ./02/client/

    - name: Build doc client
      run: dotnet publish --no-restore
      working-directory: ./02/client/

    - name: Restore dependencies server
      run: dotnet restore
      working-directory: ./01/server

    - name: Build server
      run: dotnet publish --no-restore
      working-directory: ./01/server

    - name: Restore dependencies doc server
      run: dotnet restore
      working-directory: ./02/server

    - name: Build doc server
      run: dotnet publish --no-restore
      working-directory: ./02/server

    - name: Restore dependencies operator client
      run: dotnet restore
      working-directory: ./03/client/

    - name: Build operator client
      run: dotnet publish --no-restore
      working-directory: ./03/client/

    - name: Restore dependencies operator server
      run: dotnet restore
      working-directory: ./03/server

    - name: Build operator server
      run: dotnet publish --no-restore
      working-directory: ./03/server

    - name: Restore dependencies recipe client (demo 04)
      run: dotnet restore
      working-directory: ./04/client/

    - name: Build recipe client (demo 04)
      run: dotnet publish --no-restore
      working-directory: ./04/client/

    - name: Restore dependencies recipe server (demo 04)
      run: dotnet restore
      working-directory: ./04/server/

    - name: Build recipe server (demo 04)
      run: dotnet publish --no-restore
      working-directory: ./04/server/

    - name: Restore dependencies ops client (demo 12)
      run: dotnet restore
      working-directory: ./12/client/

    - name: Build ops client (demo 12)
      run: dotnet publish --no-restore
      working-directory: ./12/client/

    - name: Restore dependencies ops server (demo 12)
      run: dotnet restore
      working-directory: ./12/server/

    - name: Build ops server (demo 12)
      run: dotnet publish --no-restore
      working-directory: ./12/server/

    - name: Restore dependencies trace client (demo 13)
      run: dotnet restore
      working-directory: ./13/client/

    - name: Build trace client (demo 13)
      run: dotnet publish --no-restore
      working-directory: ./13/client/

    - name: Restore dependencies trace server (demo 13)
      run: dotnet restore
      working-directory: ./13/server/

    - name: Build trace server (demo 13)
      run: dotnet publish --no-restore
      working-directory: ./13/server/

    - name: Restore dependencies testplan client (demo 14)
      run: dotnet restore
      working-directory: ./14/client/

    - name: Build testplan client (demo 14)
      run: dotnet publish --no-restore
      working-directory: ./14/client/

    - name: Restore dependencies testplan server (demo 14)
      run: dotnet restore
      working-directory: ./14/server/

    - name: Build testplan server (demo 14)
      run: dotnet publish --no-restore
      working-directory: ./14/server/

    - name: Restore dependencies plan-exec orchestrator client (demo 15)
      run: dotnet restore
      working-directory: ./15/client/

    - name: Build plan-exec orchestrator client (demo 15)
      run: dotnet publish --no-restore
      working-directory: ./15/client/

    - name: Restore dependencies plan executor server (demo 15)
      run: dotnet restore
      working-directory: ./15/server/

    - name: Build plan executor server (demo 15)
      run: dotnet publish --no-restore
      working-directory: ./15/server/
