# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies client
      run: dotnet restore
      working-directory: ./01/client/LLM-first/

    - name: Build client
      run: dotnet publish --no-restore
      working-directory: ./01/client/LLM-first/

    - name: Restore dependencies doc client
      run: dotnet restore
      working-directory: ./02/client/LLM-first/

    - name: Build doc client
      run: dotnet publish --no-restore
      working-directory: ./02/client/LLM-first/

    - name: Restore dependencies server
      run: dotnet restore
      working-directory: ./01/server/McpTimeServer

    - name: Build server
      run: dotnet publish --no-restore
      working-directory: ./01/server/McpTimeServer

    - name: Restore dependencies doc server
      run: dotnet restore
      working-directory: ./02/server/DocServer

    - name: Build doc server
      run: dotnet publish --no-restore
      working-directory: ./02/server/DocServer

    - name: Restore dependencies operator client
      run: dotnet restore
      working-directory: ./03/client/Orchestrator-first/

    - name: Build operator client
      run: dotnet publish --no-restore
      working-directory: ./03/client/Orchestrator-first/

    - name: Restore dependencies operator server
      run: dotnet restore
      working-directory: ./03/server/OperatorServer

    - name: Build operator server
      run: dotnet publish --no-restore
      working-directory: ./03/server/OperatorServer
